CREATE TABLE `goods_order_table` (
  `ORDER_ID` varchar(50) NOT NULL,
  `ORDER_IDX` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(50) NOT NULL,
  `ORDER_RECIEVE` varchar(50) NOT NULL,
  `USER_ADDR1` varchar(50) NOT NULL,
  `USER_ADDR2` varchar(50) NOT NULL,
  `ORDER_PHONE` varchar(50) NOT NULL,
  `TOTAL_PRICE` int(11) NOT NULL,
  `ORDER_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GDS_NUM` int(11) NOT NULL,
  PRIMARY KEY (`ORDER_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COMMENT='상품 주문 테이블';
