CREATE TABLE `goods_cart_table` (
  `CART_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(50) NOT NULL,
  `GDS_NUM` int(11) NOT NULL,
  `CART_STOCK` int(11) NOT NULL,
  `CART_ADD_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`CART_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8 COMMENT='카트 테이블';
