CREATE TABLE `goods_table` (
  `GDS_NUM` int(11) NOT NULL AUTO_INCREMENT COMMENT '상품번호',
  `GDS_NAME` varchar(50) NOT NULL COMMENT '상품이름',
  `GDS_CATEGORY_CODE` varchar(30) NOT NULL COMMENT '카테고리',
  `GDS_PRICE` int(11) NOT NULL COMMENT '상품 가격',
  `GDS_STOCK` varchar(45) DEFAULT NULL COMMENT '수량',
  `GDS_DESC` varchar(500) DEFAULT NULL COMMENT '설명',
  `GDS_IMG` varchar(300) DEFAULT NULL COMMENT '상품 이미지',
  `GDS_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록날짜',
  PRIMARY KEY (`GDS_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8 COMMENT='상품 테이블';
